sudo: required
language: go
go:
  - "1.13"
services:
  - docker
jobs:
  include:
    - if: fork = true
      stage: test
      name: docker build
      install: true
      script: make docker_build
    - stage: test
      install: make install
      name: lint
      script: make lint
    - stage: test
      name: unit tests
      install: make install
      script: make test_unit
