name: Datacatalog Checks

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  lint:
    name: Lint
    uses: flyteorg/flytetools/.github/workflows/lint.yml@master
    with:
      go-version: "1.19"

  tests:
    name: Unit Tests
    uses: flyteorg/flytetools/.github/workflows/tests.yml@master
    with:
      go-version: "1.19"
    secrets:
      FLYTE_BOT_PAT: ${{ secrets.FLYTE_BOT_PAT }}

  docker_build:
    name: Docker Build Images
    uses: flyteorg/flytetools/.github/workflows/docker_build.yml@master

  generate:
    name: Check Go Gennerate
    uses: flyteorg/flytetools/.github/workflows/go_generate.yml@master
    with:
      go-version: "1.19"

  bump_version:
    name: Bump Version
    if: ${{ github.event_name != 'pull_request' }}
    needs: [ docker_build, lint, tests, generate ] # Only to ensure it can successfully build
    uses: flyteorg/flytetools/.github/workflows/bump_version.yml@master
    secrets:
      FLYTE_BOT_PAT: ${{ secrets.FLYTE_BOT_PAT }}

  goreleaser:
    name: Goreleaser
    needs: [ bump_version ] # Only to ensure it can successfully build
    uses: flyteorg/flytetools/.github/workflows/goreleaser.yml@master
    secrets:
      FLYTE_BOT_PAT: ${{ secrets.FLYTE_BOT_PAT }}
    with:
      go-version: "1.19"

  push_docker_image:
    name: Build & Push Datacatalog Image
    needs: [ bump_version ]
    uses: flyteorg/flytetools/.github/workflows/publish.yml@master
    with:
      version: ${{ needs.bump_version.outputs.version }}
      dockerfile: Dockerfile
      push: true
      repository: ${{ github.repository }}
    secrets:
      FLYTE_BOT_PAT: ${{ secrets.FLYTE_BOT_PAT }}
      FLYTE_BOT_USERNAME: ${{ secrets.FLYTE_BOT_USERNAME }}

