name: Update flyteidl version
on: 
  workflow_dispatch:

jobs:
  update-flyte-releases:
    name: Update Flyteidl version 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Update release
        run: |
          FLYTEIDL_VERSION=$(curl --silent "https://api.github.com/repos/flyteorg/flyteidl/releases/latest" | jq -r .tag_name)
          go get -u github.com/flyteorg/flyteidl@$FLYTEIDL_VERSION
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.FLYTE_BOT_PAT }}
          commit-message: Update Flyteidl version
          committer: Flyte-Bot <admin@flyte.org>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: true
          branch: flyte-bot-update-flyteidl
          delete-branch: true
          title: 'Update Flyteidl version'
          body: |
            Update Flyteidl version
            - Auto-generated by [flyte-bot]
          labels: |
            flyteidl
          team-reviewers: |
            owners
            maintainers
          draft: false
